version: "3.7"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - students-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: manoj
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: my_school
    ports:
      - "5433:5432"
    networks:
      - students-network
    volumes:
      - postgres-students-volume:/var/lib/postgresql/data

networks:
  students-network:
    driver: bridge

volumes:
  postgres-students-volume:
